const characters = [
  {
    naam: 'Spiderman',
    kracht: 6,
    snelheid: 8,
    weerstand: 7,
    intelligentie: 8,
    type: 'superheld',
  },
  {
    naam: 'Thanos',
    kracht: 10,
    snelheid: 7,
    weerstand: 7,
    intelligentie: 7,
    type: 'schurk',
  },
  {
    naam: 'Hulk',
    kracht: 10,
    snelheid: 7,
    weerstand: 9,
    intelligentie: 3,
    type: 'superheld',
  },
  {
    naam: 'Iron Man',
    kracht: 8,
    snelheid: 10,
    weerstand: 8,
    intelligentie: 9,
    type: 'superheld',
  },
  {
    naam: 'Red Skull',
    kracht: 8,
    snelheid: 6,
    weerstand: 6,
    intelligentie: 9,
    type: 'schurk',
  },
  {
    naam: 'Captain America',
    kracht: 9,
    snelheid: 8,
    weerstand: 8,
    intelligentie: 7,
    type: 'superheld',
  },
  {
    naam: 'Malekith',
    kracht: 6,
    snelheid: 6,
    weerstand: 8,
    intelligentie: 6,
    type: 'schurk',
  },
  {
    naam: 'Dr. Strange',
    kracht: 5,
    snelheid: 7,
    weerstand: 8,
    intelligentie: 10,
    type: 'superheld',
  },
  {
    naam: 'Hela',
    kracht: 9,
    snelheid: 6,
    weerstand: 4,
    intelligentie: 8,
    type: 'schurk',
  },
  {
    naam: 'Thor',
    kracht: 9,
    snelheid: 8,
    weerstand: 7,
    intelligentie: 5,
    type: 'superheld',
  },
  {
    naam: 'Laufey',
    kracht: 7,
    snelheid: 7,
    weerstand: 6,
    intelligentie: 8,
    type: 'schurk',
  },
  {
    naam: 'Ant-Man',
    kracht: 6,
    snelheid: 7,
    weerstand: 7,
    intelligentie: 7,
    type: 'superheld',
  },
];
